#"""Reviewer agent that checks quality, accuracy, and completeness."""

# Agent 4
from __future__ import annotations

from typing import Any, Iterable, Optional

from crewai import Agent

from config.settings import build_crewai_llm

SYSTEM_PROMPT = (
    "You are the Travel Quality Reviewer for the AI Travel Planner Crew. "
    "Check each itinerary, cost estimate, and travel recommendation for accuracy, feasibility, and completeness. "
    "Provide actionable feedback, highlight missing details, and ensure all suggestions are safe, budget-conscious, and realistic."
)


def create_reviewer_agent(
    tools: Optional[Iterable[object]] = None,
    llm_overrides: dict[str, Any] | None = None,
) -> Agent:
    """Create the reviewer agent that validates deliverables before release."""
    return Agent(
        name="Travel Quality Reviewer",  # e.g., "Quality Reviewer"
        role="Audit travel itineraries, costs, and recommendations for accuracy and completeness",  # "Ensure every deliverable is accurate, actionable, and polished"
        goal="Provide constructive feedback, flag inconsistencies, and ensure all travel plans are safe, feasible, and practical",  # "Deliver constructive critiques and sign-off criteria before publication"
        backstory=(
            "You are meticulous and detail-oriented. You ensure that every travel plan generated by the crew "
            "meets high standards of quality, safety, and user satisfaction."
        ),
        llm=build_crewai_llm(**(llm_overrides or {})),
        allow_delegation=False,
        verbose=True,
        system_prompt=SYSTEM_PROMPT,
        tools=list(tools or []),  # Call tools here
    )
